### PR TITLE
Find Ogre (fix #78).

### LINKED ISSUE #78: Compilation fails with Ogre 1.9 on Arch Linux
``` shell
moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp:52:
/opt/ros/hydro/include/rviz/ogre_helpers/qt_ogre_render_window.h:36:29: fatal error: OgreColourValue.h: No such file or directory
 #include <OgreColourValue.h>
                             ^
```

A possible solution is to do what was done in rviz: https://github.com/ros-visualization/rviz/commit/ab9b99a1990a5f58b19292307bc4346258cdde14

### PR DESCRIPTION
**Pull request by bchretien**

### CODE REVIEW

**Comment by hersh** [comment]
It should not be necessary to duplicate the CMake code in RViz.  The RViz changes include exports of Ogre libraries and include paths.  The fact that moveit_setup_assistant depends on rviz should mean that this just works.

Have you tried building moveit_setup_assistant in this situation with RViz from trunk?

**Comment by bchretien** [comment]
@hersh: I tried with the latest release of RViz, yet include_dirs seemed to be missing.

**Comment by hersh** [comment]
Well, Acorn is out on vacation this week, but it is definitely one of the goals of the rviz change that it should not be necessary to duplicate that change everywhere downstream of rviz.  Maybe try making moveit_setup_assistant directly depend on rviz, instead of depending on it through moveit_ros_visualization.  It may be that moveit_ros_visualization is not passing on something that it should be.

(Even that should not be necessary of course, but it might show whether the problem is in exports from rviz or in the passing-on of exports within moveit_ros_visualization.)

**Comment by bchretien** [comment]
``` cmake
message("rviz_INCLUDE_DIRS: ${rviz_INCLUDE_DIRS}")
message("rviz_LIBRARIES: ${rviz_LIBRARIES}")
```

``` shell
rviz_INCLUDE_DIRS: /opt/ros/hydro/include;/usr/include;/opt/ros/hydro/include/opencv;/usr/include/eigen3
rviz_LIBRARIES: /opt/ros/hydro/lib/librviz.so;/opt/ros/hydro/lib/libdefault_plugin.so;/usr/lib64/libOgreOverlay.so;/usr/lib64/libOgreMain.so;/usr/lib64/libGLU.so;/usr/lib64/libGL.so;/usr/lib64/libSM.so;/usr/lib64/libICE.so;/usr/lib64/libX11.so;/usr/lib64/libXext.so;/opt/ros/hydro/lib/libimage_geometry.so;/opt/ros/hydro/lib/libimage_transport.so;/opt/ros/hydro/lib/libinteractive_markers.so;/opt/ros/hydro/lib/liblaser_geometry.so;/usr/lib64/libtinyxml.so;/opt/ros/hydro/lib/libclass_loader.so;/usr/lib64/libPocoFoundation.so;/usr/lib64/libdl.so;/opt/ros/hydro/lib/libresource_retriever.so;/opt/ros/hydro/lib/libroslib.so;/opt/ros/hydro/lib/libtf.so;/opt/ros/hydro/lib/libtf2_ros.so;/opt/ros/hydro/lib/libactionlib.so;/opt/ros/hydro/lib/libmessage_filters.so;/opt/ros/hydro/lib/libtf2.so;/opt/ros/hydro/lib/liburdf.so;/opt/ros/hydro/lib/liburdfdom_sensor.so;/opt/ros/hydro/lib/liburdfdom_model_state.so;/opt/ros/hydro/lib/liburdfdom_model.so;/opt/ros/hydro/lib/liburdfdom_world.so;/opt/ros/hydro/lib/librosconsole_bridge.so;/opt/ros/hydro/lib/libroscpp.so;/usr/lib64/libpthread.so;/usr/lib64/libboost_signals.so;/usr/lib64/libboost_filesystem.so;/opt/ros/hydro/lib/librosconsole.so;/opt/ros/hydro/lib/librosconsole_log4cxx.so;/opt/ros/hydro/lib/librosconsole_backend_interface.so;/usr/lib64/liblog4cxx.so;/usr/lib64/libboost_regex.so;/opt/ros/hydro/lib/libxmlrpcpp.so;/opt/ros/hydro/lib/libroscpp_serialization.so;/opt/ros/hydro/lib/librostime.so;/usr/lib64/libboost_date_time.so;/usr/lib64/libboost_system.so;/usr/lib64/libboost_thread.so;/opt/ros/hydro/lib/libcpp_common.so;/opt/ros/hydro/lib/libconsole_bridge.so
```

``` cmake
message("moveit_ros_visualization_INCLUDE_DIRS: ${moveit_ros_visualization_INCLUDE_DIRS}")
message("moveit_ros_visualization_LIBRARIES: ${moveit_ros_visualization_LIBRARIES}")
```

``` shell
moveit_ros_visualization_INCLUDE_DIRS: /opt/ros/hydro/include;/usr/include;/usr/include/eigen3
moveit_ros_visualization_LIBRARIES: /opt/ros/hydro/lib/libmoveit_rviz_plugin_render_tools.so;/opt/ros/hydro/lib/libmoveit_robot_state_rviz_plugin_core.so;/opt/ros/hydro/lib/libmoveit_motion_planning_rviz_plugin_core.so;/opt/ros/hydro/lib/libmoveit_planning_scene_rviz_plugin_core.so;/opt/ros/hydro/lib/libmoveit_common_planning_interface_objects.so;/opt/ros/hydro/lib/libmoveit_planning_scene_interface.so;/opt/ros/hydro/lib/libmoveit_move_group_interface.so;/opt/ros/hydro/lib/libmoveit_warehouse.so;/opt/ros/hydro/lib/libwarehouse_ros.so;/opt/ros/hydro/lib/libmoveit_pick_place_planner.so;/opt/ros/hydro/lib/libmoveit_move_group_capabilities_base.so;/opt/ros/hydro/lib/libmoveit_robot_interaction.so;/opt/ros/hydro/lib/libmoveit_rdf_loader.so;/opt/ros/hydro/lib/libmoveit_kinematics_plugin_loader.so;/opt/ros/hydro/lib/libmoveit_robot_model_loader.so;/opt/ros/hydro/lib/libmoveit_constraint_sampler_manager_loader.so;/opt/ros/hydro/lib/libmoveit_planning_pipeline.so;/opt/ros/hydro/lib/libmoveit_trajectory_execution_manager.so;/opt/ros/hydro/lib/libmoveit_plan_execution.so;/opt/ros/hydro/lib/libmoveit_planning_scene_monitor.so;/opt/ros/hydro/lib/libmoveit_point_containment_filter.so;/opt/ros/hydro/lib/libmoveit_occupancy_map_monitor.so;/opt/ros/hydro/lib/libmoveit_pointcloud_octomap_updater_core.so;/opt/ros/hydro/lib/libmoveit_semantic_world.so;/opt/ros/hydro/lib/libmoveit_exceptions.so;/opt/ros/hydro/lib/libmoveit_background_processing.so;/opt/ros/hydro/lib/libmoveit_kinematics_base.so;/opt/ros/hydro/lib/libmoveit_robot_model.so;/opt/ros/hydro/lib/libmoveit_transforms.so;/opt/ros/hydro/lib/libmoveit_robot_state.so;/opt/ros/hydro/lib/libmoveit_robot_trajectory.so;/opt/ros/hydro/lib/libmoveit_planning_interface.so;/opt/ros/hydro/lib/libmoveit_collision_detection.so;/opt/ros/hydro/lib/libmoveit_collision_detection_fcl.so;/opt/ros/hydro/lib/libmoveit_kinematic_constraints.so;/opt/ros/hydro/lib/libmoveit_planning_scene.so;/opt/ros/hydro/lib/libmoveit_constraint_samplers.so;/opt/ros/hydro/lib/libmoveit_planning_request_adapter.so;/opt/ros/hydro/lib/libmoveit_profiler.so;/opt/ros/hydro/lib/libmoveit_trajectory_processing.so;/opt/ros/hydro/lib/libmoveit_distance_field.so;/opt/ros/hydro/lib/libmoveit_kinematics_metrics.so;/opt/ros/hydro/lib/libmoveit_dynamics_solver.so;/usr/lib64/libboost_iostreams.so;/opt/ros/hydro/lib/libgeometric_shapes.so;/opt/ros/hydro/lib/liboctomap.so;/opt/ros/hydro/lib/liboctomath.so;/opt/ros/hydro/lib/libshape_tools.so;/opt/ros/hydro/lib/libeigen_conversions.so;/opt/ros/hydro/lib/librandom_numbers.so;/opt/ros/hydro/lib/libkdl_parser.so;/opt/ros/hydro/lib/liburdf.so;/opt/ros/hydro/lib/liburdfdom_sensor.so;/opt/ros/hydro/lib/liburdfdom_model_state.so;/opt/ros/hydro/lib/liburdfdom_model.so;/opt/ros/hydro/lib/liburdfdom_world.so;/opt/ros/hydro/lib/librosconsole_bridge.so;/opt/ros/hydro/lib/libsrdfdom.so;/opt/ros/hydro/lib/libimage_transport.so;/usr/lib64/libtinyxml.so;/opt/ros/hydro/lib/libclass_loader.so;/usr/lib64/libPocoFoundation.so;/usr/lib64/libdl.so;/opt/ros/hydro/lib/libroslib.so;/opt/ros/hydro/lib/libinteractive_markers.so;/opt/ros/hydro/lib/libtf.so;/opt/ros/hydro/lib/libtf2_ros.so;/opt/ros/hydro/lib/libactionlib.so;/opt/ros/hydro/lib/libmessage_filters.so;/opt/ros/hydro/lib/libroscpp.so;/usr/lib64/libpthread.so;/usr/lib64/libboost_signals.so;/usr/lib64/libboost_filesystem.so;/opt/ros/hydro/lib/libxmlrpcpp.so;/opt/ros/hydro/lib/libtf2.so;/opt/ros/hydro/lib/librosconsole.so;/opt/ros/hydro/lib/librosconsole_log4cxx.so;/opt/ros/hydro/lib/librosconsole_backend_interface.so;/usr/lib64/liblog4cxx.so;/usr/lib64/libboost_regex.so;/opt/ros/hydro/lib/libroscpp_serialization.so;/opt/ros/hydro/lib/librostime.so;/usr/lib64/libboost_date_time.so;/usr/lib64/libboost_system.so;/usr/lib64/libboost_thread.so;/opt/ros/hydro/lib/libcpp_common.so;/opt/ros/hydro/lib/libconsole_bridge.so
```

So libraries seem to be right (Ogre is indeed there), but not include directories.

Also, depending directly on `rviz` does not seem to change anything. I'll keep on investigating and get back to you.

**Comment by bchretien** [comment]
@hersh: Ok, you may be able to explain this. While packaging `rviz`, I can find 2 `rvizConfig.cmake` files in the build directory:
- `src/build/devel/share/rviz/cmake/rvizConfig.cmake` in which we can find:
  
  ``` cmake
  set(_include_dirs "/home/user/arch-ros-stacks/hydro/rviz/src/rviz/src;/usr/include/eigen3;/usr/include/OGRE/Overlay;/usr/include/OGRE;/usr/include;/opt/ros/hydro/include;/opt/ros/hydro/include;/opt/ros/hydro/include")
  ```
- `src/build/catkin_generated/installspace/rvizConfig.cmake` in which we have:
  
  ``` cmake
  set(_include_dirs "include")
  ```

In the first one, `_include_dirs` contains the OGRE include directories. But not in the second one, which is the one that is being installed.

FYI, the packaging command for Arch Linux is:

``` shell
  cmake ${srcdir}/${_dir} \
        -DCMAKE_BUILD_TYPE=Release \
        -DCATKIN_BUILD_BINARY_PACKAGE=ON \
        -DCMAKE_INSTALL_PREFIX=/opt/ros/hydro \
        -DPYTHON_EXECUTABLE=/usr/bin/python2 \
        -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 \
        -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so \
        -DSETUPTOOLS_DEB_LAYOUT=OFF
  make
```

**Comment by bchretien** [comment]
Cf. https://github.com/ros-visualization/rviz/issues/730

I'll close this as soon as we fix the rviz problem.

**Pull request merged**
