### PR TITLE
Generate joint_limits.yaml using ordered joints

### PR DESCRIPTION
**Pull request by davetcoleman**
The `std::sort` structure was storing pointers, so I believe it was populating its binary search trees based on memory address locations, I've added a custom comparator that instead compares the joint model's names, ensureing alphabetical ordering. 

Fix for https://github.com/ros-planning/moveit_setup_assistant/issues/53

### CODE REVIEW

**Comment by isucan** [comment]
+1

**Comment by hersh** [comment]
I just ran this and the joints in joint_limits.yaml were still not in alphabetical order.  Does this work for you?

**Comment by hersh** [comment]
oop, hold on, ran with wrong ROS_PACKAGE_PATH...

**Comment by hersh** [comment]
ok, works fine. :)

**Pull request merged**
