### PR TITLE
Changed default maintainer and author for generated pkgs

### PR DESCRIPTION
**Pull request by davetcoleman**
Per https://github.com/ros-planning/moveit_setup_assistant/issues/110

A pretty lazy solution, but I doubt anyone has time to modify the GUI to take this input and this will work until then.

### CODE REVIEW

**Comment by 130s** [comment]
So if the package creator doesn't update the `maintainer` element upon creation, ROS buildfarm would send emails to `todo@todo.todo`. Will that be ok @tfoote?

**Comment by v4hn** [comment]
What else to do on Friday afternoon...

https://github.com/v4hn/moveit_setup_assistant/commit/3181604e8bf203fe49efd5e02f653006b232b841

This goes at least 50% of the way. Maybe someone can fix it up/ load the strings if available/ make sure the strings are not empty?
I might get around to finish this next week.

**Comment by tfoote** [comment]
+1 for @v4hn 's approach having invalid maintainer emails is a problem for sustainability.

**Comment by davetcoleman** [comment]
wow good start on that!

**Pull request closed without merging**
