### PR TITLE
Fix for issue #70: support yaml-cpp 0.5+ (new api).

### PR DESCRIPTION
**Pull request by hersh**
Hopefully this fixes issue #70.  I have only tested it on Ubuntu Precise, which uses the old API.

Before this is merged I would like someone with the new API to compile and test this.

Thanks.

### CODE REVIEW

**Comment by sachinchitta** [comment]
@bchretien - could you please comment on whether this fixes things for you so we can close it.

**Comment by bchretien** [comment]
@sachinchitta: it still fails for now. Iterators changed as well apparently (`YAML::Iterator` in yaml-cpp 0.3, `YAML::(const_)iterator` in yaml-cpp 0.5), `FindValue` no longer exists etc. I can try to find some spare time to fix it.

**Comment by bchretien** [comment]
I uploaded a quick fix for yaml-cpp 0.5 (compiles but not tested, and breaks with yaml-cpp 0.3): https://github.com/bchretien/moveit_setup_assistant/commit/b9e7d041b1cb658288b5a6f4a281f436d6269665

This should give you an idea of the changes to expect.

**Comment by bchretien** [comment]
@hersh @sachinchitta I made a more complex patch for yaml-cpp 0.3 and 0.5 (0d2e04e). Iterators changed, `FindValue` was removed, and they moved from a C-style API to a C++-style API, so my patch involves some dirty tricks. There are better ways to handle that, but this should finally work with both APIs. Could you guys test it?

The only test I made was running the assistant on a URDF with yaml-cpp 0.5, but I may not have tested the right things though.

**Comment by bchretien** [comment]
New patch: https://github.com/bchretien/moveit_setup_assistant/commit/918bd220f51e3fdd73e92f55fd4a7ce7b8428380

Tested on Arch Linux with yaml-cpp 0.5: create, save, reload. I'll try to test with yaml-cpp 0.3.

**Comment by bchretien** [comment]
Tested with yaml-cpp 0.3 as well. Everything seems to compile/run correctly.

**Comment by hersh** [comment]
@bchretien thanks for your help.

**Comment by bchretien** [comment]
@hersh no problem! ;-)

**Comment by costashatz** [comment]
When trying to load an existing MoveIt! configuration package, I get the following error:

```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.


terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  yaml-cpp: error at line 0, column 0: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
```

And here's the backtrace:

```
#0  0x00007ffff5911d67 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff5913118 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff5f02dc5 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/libstdc++.so.6
#3  0x00007ffff5f00e46 in ?? () from /usr/lib/libstdc++.so.6
#4  0x00007ffff5f00e91 in std::terminate() () from /usr/lib/libstdc++.so.6
#5  0x00007ffff5f010f6 in __cxa_rethrow () from /usr/lib/libstdc++.so.6
#6  0x00007ffff6afb646 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#7  0x00007ffff6b00719 in QCoreApplication::exec() ()
   from /usr/lib/libQtCore.so.4
#8  0x0000000000408fa2 in main ()
```

I have compiled the ROS packages using yaml-cpp0.5 and I am running them with the same version of course..Any ideas??

Thanks...

**Pull request merged**
