### PR TITLE
add collision spheres

### PR DESCRIPTION
**Pull request by acornacorn**
add support for writing collision spheres to SRDF.

DEPENDS ON: https://github.com/ros-planning/srdfdom/pull/1

### CODE REVIEW

**Comment by acornacorn** [comment]
updated according to Ioan's comments.
THIS PULL DEPENDS ON https://github.com/ros-planning/srdfdom/pull/1

**Comment by isucan** [comment]
I merged the dependency pull req; unless you need this now, I recommend waiting a bit, until the new srdfdom pkg is in debs, so users do not need to pull it from source. Would this be ok?

**Comment by isucan** [comment]
updated srdfdom is in public repos now

**Comment by davetcoleman** [comment]
yay collision spheres!

**Pull request merged**
